### ISSUE TITLE
Download tsimulus-cli JAR

### ISSUE THREAD

**Issue by kirand1303** [cetic/tsimulus-cli#3]
Hello,

From where do I download tsimulus-cli.jar. I see only rts-gen-console.jar.

Also when I do a  java -jar rts-gen-console.jar configuration.json I get file not found exception.

Would you please provide steps to install and use the application. Whatever steps mentioned in readme file does not help much.

Thanks.

**Comment by LibertyWalk** [comment]
I'm facing the same problem. Any updates on this?

**Comment by mgoeminne** [comment]
rts-gen is the former name of tsimulus. More precisely, rts-gen was the generator library, that has been renamed as [TSimulus](https://github.com/cetic/TSimulus).

The archive has been renamed accordingly, with [tsimulus-cli v1.1](https://github.com/cetic/tsimulus-cli/releases/tag/v1.1)

I close this ticket.
